// <auto-generated />
using BeerTasting.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeerAPI.Migrations
{
    [DbContext(typeof(BeerTastingDbContext))]
    partial class BeerTastingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeerAPI.Models.Entities.Beer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Abv")
                        .HasColumnType("double precision");

                    b.Property<string>("Brewery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCatalogBeer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TastingId")
                        .HasColumnType("text");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TastingId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Abv = 5.2000000000000002,
                            Brewery = "Ægir Brugghús ehf.",
                            IsCatalogBeer = true,
                            Name = "Ægir Jólalager",
                            Style = "Christmas Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "2",
                            Abv = 7.5,
                            Brewery = "RVK Bruggfélag",
                            IsCatalogBeer = true,
                            Name = "Ákaflega gaman þá Double IPA",
                            Style = "IPA",
                            VolumeMl = 440
                        },
                        new
                        {
                            Id = "3",
                            Abv = 7.0,
                            Brewery = "Royal Unibrew A/S",
                            IsCatalogBeer = true,
                            Name = "Albani Jule Bryg Blaa Lys",
                            Style = "Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "4",
                            Abv = 10.5,
                            Brewery = "Lady Brewery ehf.",
                            IsCatalogBeer = true,
                            Name = "Antichrist Imperial Stout",
                            Style = "Imperial Stout",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "5",
                            Abv = 5.4000000000000004,
                            Brewery = "Borg Brugghús",
                            IsCatalogBeer = true,
                            Name = "Askasleikir nr. 45 Amber Ale",
                            Style = "Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "6",
                            Abv = 6.7000000000000002,
                            Brewery = "Borg Brugghús",
                            IsCatalogBeer = true,
                            Name = "Áttavittur nr. 116 Double Bock",
                            Style = "Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "7",
                            Abv = 6.5,
                            Brewery = "Lady Brewery ehf.",
                            IsCatalogBeer = true,
                            Name = "Be Merry Me Berry",
                            Style = "Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "8",
                            Abv = 5.0,
                            Brewery = "Ölgerðin Egill Skallagrímsson",
                            IsCatalogBeer = true,
                            Name = "Boli X Mas",
                            Style = "Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "9",
                            Abv = 0.0,
                            Brewery = "Borg",
                            IsCatalogBeer = true,
                            Name = "Brió 0%",
                            Style = "Non-Alcoholic",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "10",
                            Abv = 8.5,
                            Brewery = "Corsendonk",
                            IsCatalogBeer = true,
                            Name = "Corsendonk Christmas Ale",
                            Style = "Christmas Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "11",
                            Abv = 5.5999999999999996,
                            Brewery = "Gæðingur-Öl ehf",
                            IsCatalogBeer = true,
                            Name = "Dagsson jólabjór með bubblum",
                            Style = "Christmas Ale",
                            VolumeMl = 330
                        },
                        new
                        {
                            Id = "12",
                            Abv = 6.0,
                            Brewery = "Einstök Ölgerð",
                            IsCatalogBeer = true,
                            Name = "Einstök Winter Ale",
                            Style = "Winter Ale",
                            VolumeMl = 330
                        });
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TastingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TastingId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Rating", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BeerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("TastingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TastingId", "ParticipantId", "BeerId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Tasting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentBeerIndex")
                        .HasColumnType("integer");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlind")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tastings");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Beer", b =>
                {
                    b.HasOne("BeerAPI.Models.Entities.Tasting", "Tasting")
                        .WithMany("BeerList")
                        .HasForeignKey("TastingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tasting");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Participant", b =>
                {
                    b.HasOne("BeerAPI.Models.Entities.Tasting", "Tasting")
                        .WithMany("Participants")
                        .HasForeignKey("TastingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tasting");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Rating", b =>
                {
                    b.HasOne("BeerAPI.Models.Entities.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerAPI.Models.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerAPI.Models.Entities.Tasting", "Tasting")
                        .WithMany("Ratings")
                        .HasForeignKey("TastingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Participant");

                    b.Navigation("Tasting");
                });

            modelBuilder.Entity("BeerAPI.Models.Entities.Tasting", b =>
                {
                    b.Navigation("BeerList");

                    b.Navigation("Participants");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
